# Generated by Django 2.0.8 on 2018-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxesStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('dhcpcd', models.BooleanField(default=False)),
                ('dhcpcd_message', models.TextField(default='')),
                ('dnsmasq', models.BooleanField(default='')),
                ('dnsmasq_message', models.TextField(default='')),
                ('hostapd', models.BooleanField(default=False)),
                ('hostapd_message', models.TextField(default='')),
                ('nodogsplash', models.BooleanField(default=False)),
                ('connected_clients', models.IntegerField(default=0)),
                ('nodogsplash_message', models.TextField(default='')),
                ('internet_connection', models.BooleanField(default=False)),
                ('internet_connection_message', models.TextField(default='')),
            ],
        ),
    ]
