# Generated by Django 2.2.dev20180916104534 on 2018-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostumeLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('internet', models.CharField(max_length=200)),
                ('ip_adress', models.CharField(max_length=200)),
                ('nodogsplash_status', models.CharField(max_length=200)),
                ('hostapd_status', models.CharField(max_length=200)),
            ],
        ),
    ]
