# Generated by Django 2.2.dev20180916104534 on 2018-10-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='bouraoui', max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
