# Generated by Django 2.2.dev20180916104534 on 2018-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('api_key', models.CharField(max_length=200)),
                ('api_host', models.CharField(default='api.way-connect.com', max_length=200)),
                ('api_port', models.IntegerField(default=80)),
                ('api_secret', models.CharField(max_length=200)),
                ('root_dir', models.CharField(default='/home/bouraoui', max_length=200)),
                ('version', models.CharField(default='0.0.1', max_length=200)),
                ('patch', models.CharField(default='0.0.1', max_length=200)),
                ('app_dir', models.CharField(default='Way-Connect_Box', max_length=200)),
                ('git_repo', models.CharField(default='https://github.com/alaxa27/Way-Connect_Box.git', max_length=200)),
                ('ftp_host', models.CharField(default='127.0.0.1', max_length=200)),
                ('ftp_user', models.CharField(default='user', max_length=200)),
                ('ftp_password', models.CharField(default='password', max_length=200)),
                ('api_mode', models.CharField(choices=[('wlan', 'wlan'), ('eth', 'eth')], max_length=200)),
            ],
        ),
    ]
