# Generated by Django 2.2.dev20180916104534 on 2018-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0002_auto_20181003_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='ssid_prefix',
            field=models.CharField(default='_FREE_WIFI', max_length=200),
        ),
    ]
