# Generated by Django 2.2.dev20180916104534 on 2018-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0004_dnsmasq_hostapd'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('params', models.TextField()),
            ],
        ),
    ]
