# Generated by Django 2.2.dev20180916104534 on 2018-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0009_hosts_ipset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsmasq',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='bind_interfaces',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='bogus_priv',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='dhcp_range',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='domain_needed',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='ipset',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='listen_address',
        ),
        migrations.RemoveField(
            model_name='dnsmasq',
            name='server',
        ),
        migrations.RemoveField(
            model_name='hostapd',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='hostapd',
            name='hw_mode',
        ),
        migrations.RemoveField(
            model_name='hostapd',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='hostapd',
            name='macaddr_acl',
        ),
        migrations.RemoveField(
            model_name='hostapd',
            name='ssid',
        ),
        migrations.AddField(
            model_name='dnsmasq',
            name='params',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hostapd',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hostapd',
            name='params',
            field=models.TextField(default=''),
        ),
    ]
