# Generated by Django 2.2.dev20180916104534 on 2018-10-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0010_auto_20181010_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('params', models.TextField(default='')),
                ('api_mode', models.CharField(choices=[('wlan', 'wlan'), ('eth', 'eth')], max_length=200)),
                ('setting_type', models.CharField(choices=[('ipset', 'ipset'), ('iptables', 'iptables'), ('dnsmask', 'dnsmask'), ('hostapd', 'hostapd'), ('hosts', 'hosts'), ('interfaces', 'Network interfaces'), ('nodogsplash', 'Nodogsplash')], max_length=200)),
                ('origine', models.CharField(default='', max_length=200)),
                ('dest', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Dnsmasq',
        ),
        migrations.DeleteModel(
            name='Hostapd',
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
        migrations.DeleteModel(
            name='Interfaces',
        ),
        migrations.DeleteModel(
            name='Ipset',
        ),
        migrations.DeleteModel(
            name='IpTables',
        ),
        migrations.DeleteModel(
            name='Nodogsplash',
        ),
    ]
