# Generated by Django 2.2.dev20180916104534 on 2018-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0012_env_client_session_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='client_session_timeout',
            field=models.IntegerField(choices=[(30, '30 minute'), (60, '1 heure')], default=30, max_length=200),
        ),
    ]
