# Generated by Django 2.2.dev20180916104534 on 2018-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0013_auto_20181016_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledSoftwares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='env',
            name='client_session_timeout',
            field=models.IntegerField(choices=[(30, '30 minute'), (60, '1 heure')], default=30),
        ),
    ]
