# Generated by Django 2.2.dev20180916104534 on 2018-10-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0016_auto_20181017_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='cmd_next',
            field=models.CharField(default='', max_length=200),
        ),
    ]
