# Generated by Django 2.2.dev20180916104534 on 2018-11-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_ftputils_httphandler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworksUtils',
        ),
    ]
