# Generated by Django 2.0.8 on 2018-11-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_delete_networksutils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HttpHandler',
            new_name='WebFunctions',
        ),
    ]
