# Generated by Django 2.0.8 on 2018-11-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_auto_20181109_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebFunctions',
            new_name='Httphandler',
        ),
    ]
