# Generated by Django 2.1.3 on 2018-11-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20181113_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FtpUtils',
        ),
    ]
