# Generated by Django 2.0.8 on 2018-11-16 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('dhcpcd', models.BooleanField(default=False)),
                ('dhcpcd_message', models.TextField(default='')),
                ('dnsmasq', models.BooleanField(default='')),
                ('dnsmasq_message', models.TextField(default='')),
                ('hostapd', models.BooleanField(default=False)),
                ('hostapd_message', models.TextField(default='')),
                ('nodogsplash', models.BooleanField(default=False)),
                ('connected_clients', models.IntegerField(default=0)),
                ('nodogsplash_message', models.TextField(default='')),
                ('internet_connection', models.BooleanField(default=False)),
                ('internet_connection_message', models.TextField(default='')),
                ('patch_version', models.CharField(default='', max_length=200)),
                ('branch', models.CharField(default='', max_length=200)),
                ('git_hash', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.FileField(upload_to='uploads/')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('patches_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.Patches')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.CharField(default='', max_length=200)),
                ('git_hash', models.CharField(default='', max_length=200)),
                ('patches_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boxes.Patches')),
            ],
        ),
    ]
