# Generated by Django 2.0.8 on 2018-11-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateinformation',
            name='patches_id',
        ),
        migrations.RemoveField(
            model_name='patches',
            name='deleted',
        ),
        migrations.DeleteModel(
            name='UpdateInformation',
        ),
    ]
