# Generated by Django 2.0.8 on 2018-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_auto_20181116_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxstatus',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='connected_clients',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='dhcpcd',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='dhcpcd_message',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='dnsmasq',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='git_hash',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='hostapd',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='internet_connection',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='nodogsplash',
        ),
        migrations.RemoveField(
            model_name='boxstatus',
            name='patch_version',
        ),
        migrations.AddField(
            model_name='boxstatus',
            name='connected_customers',
            field=models.PositiveIntegerField(default=0, verbose_name='customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxstatus',
            name='dhcpd_message',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='boxstatus',
            name='dhcpd_running',
            field=models.BooleanField(default=False, verbose_name='DHCPD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxstatus',
            name='dnsmasq_running',
            field=models.BooleanField(default=False, verbose_name='DNSMASQ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxstatus',
            name='hostapd_running',
            field=models.BooleanField(default=False, verbose_name='HOSTAPD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxstatus',
            name='internet_connection_active',
            field=models.BooleanField(default=False, verbose_name='internet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxstatus',
            name='nodogsplash_running',
            field=models.BooleanField(default=False, verbose_name='NDS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxstatus',
            name='dnsmasq_message',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='boxstatus',
            name='hostapd_message',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='boxstatus',
            name='internet_connection_message',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='boxstatus',
            name='nodogsplash_message',
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
    ]
