# Generated by Django 2.1.3 on 2018-11-19 09:11

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('boxes', '0003_auto_20181116_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patches',
            new_name='Patch',
        ),
        migrations.DeleteModel(
            name='BoxStatus',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='patches_id',
            new_name='patch',
        ),
    ]
