# Generated by Django 2.1.3 on 2018-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_auto_20181119_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
