# Generated by Django 2.2.dev20180916104534 on 2018-10-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0003_env_ssid_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dnsmasq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(default='wlan0', max_length=200)),
                ('listen_address', models.CharField(default='192.168.220.2', max_length=200)),
                ('bind_interfaces', models.CharField(default='g', max_length=200)),
                ('server', models.CharField(default='8.8.8.8', max_length=200)),
                ('domain_needed', models.CharField(default='True', max_length=200)),
                ('bogus_priv', models.CharField(default='True', max_length=200)),
                ('dhcp_range', models.CharField(default='192.168.220.20,192.168.220.150,12h', max_length=200)),
                ('address', models.CharField(default='/w.zone/192.168.220.2', max_length=200)),
                ('ipset', models.CharField(default='/way-connect.com/use.fontawesome.com/fonts.googleapis.com/storage.googleapis.com/wc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hostapd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(default='wlan0', max_length=200)),
                ('ssid', models.CharField(default='Way-Box_FREEWIFI', max_length=200)),
                ('hw_mode', models.CharField(default='g', max_length=200)),
                ('channel', models.CharField(default='11', max_length=200)),
                ('macaddr_acl', models.CharField(default='0', max_length=200)),
            ],
        ),
    ]
