# Generated by Django 2.2.dev20180916104534 on 2018-10-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0006_interfaces_nodogsplash'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsmasq',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
