# Generated by Django 2.2.dev20180916104534 on 2018-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0007_dnsmasq_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsmasq',
            name='dest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hostapd',
            name='dest',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='interfaces',
            name='dest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='iptables',
            name='dest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='nodogsplash',
            name='dest',
            field=models.CharField(default='', max_length=200),
        ),
    ]
