# Generated by Django 2.2.dev20180916104534 on 2018-10-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0008_auto_20181005_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('params', models.TextField()),
                ('dest', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('params', models.TextField()),
                ('dest', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
