# Generated by Django 2.2.dev20180916104534 on 2018-10-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0011_auto_20181012_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='client_session_timeout',
            field=models.CharField(choices=[(30, '30 minute'), ('60', '1 heure')], default=30, max_length=200),
        ),
    ]
