# Generated by Django 2.2.dev20180916104534 on 2018-10-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0015_auto_20181017_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settingapp',
            name='setting_type',
            field=models.CharField(choices=[('ipset', 'ipset'), ('iptables', 'iptables'), ('dnsmasq', 'dnsmasq'), ('hostapd', 'hostapd'), ('hosts', 'hosts'), ('interfaces', 'Network interfaces'), ('nodogsplash', 'Nodogsplash')], max_length=200),
        ),
    ]
