# Generated by Django 2.2.dev20180916104534 on 2018-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0018_settingapp_command_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
