# Generated by Django 2.2.dev20180916104534 on 2018-10-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0019_settingapp_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='command_type_next',
            field=models.CharField(choices=[('sh', 'Sh'), ('cmd', 'cmd')], default='cmd', max_length=200),
        ),
    ]
