# Generated by Django 2.2.dev20180916104534 on 2018-10-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0022_auto_20181031_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='middleware_dir',
            field=models.CharField(default='', max_length=200),
        ),
    ]
