# Generated by Django 2.2.dev20180916104534 on 2018-10-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0023_env_middleware_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='databases_backup_dir',
            field=models.CharField(default='databases_backups', max_length=200),
        ),
        migrations.AlterField(
            model_name='env',
            name='middleware_dir',
            field=models.CharField(default='middleware', max_length=200),
        ),
    ]
