# Generated by Django 2.2.dev20180916104534 on 2018-10-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0024_auto_20181031_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='directory',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='settingapp',
            name='sup_directory',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='settingapp',
            name='cmd',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='settingapp',
            name='cmd_next',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
