# Generated by Django 2.2.dev20180916104534 on 2018-10-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0026_auto_20181031_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='config_dir',
            field=models.CharField(default='opt/config/', max_length=200),
        ),
    ]
