# Generated by Django 2.2.dev20180916104534 on 2018-11-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0027_env_config_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='settingapp',
            name='setting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env_config.SettingTypes'),
        ),
    ]
