# Generated by Django 2.2.dev20180916104534 on 2018-11-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0028_auto_20181102_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingapp',
            options={'ordering': ('sequence',)},
        ),
        migrations.RemoveField(
            model_name='settingtypes',
            name='name',
        ),
    ]
