# Generated by Django 2.2.dev20180916104534 on 2018-11-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0030_settingtypes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
