# Generated by Django 2.2.dev20180916104534 on 2018-11-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0031_settingapp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingapp',
            name='cmd_status',
            field=models.CharField(blank=True, default='systemctl status', max_length=200),
        ),
    ]
