# Generated by Django 2.2.dev20180916104534 on 2018-11-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0032_settingapp_cmd_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstalledSoftwares',
        ),
        migrations.AddField(
            model_name='env',
            name='origin_config_dir',
            field=models.CharField(default='opt/original files/', max_length=200),
        ),
        migrations.DeleteModel(
            name='SettingApp',
        ),
        migrations.DeleteModel(
            name='SettingTypes',
        ),
    ]
