# Generated by Django 2.2.dev20180916104534 on 2018-11-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0033_auto_20181105_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='etc_dir',
            field=models.CharField(default='/etc', max_length=200),
        ),
    ]
