# Generated by Django 2.0.8 on 2018-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0035_env_run_on_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='databases_backup_dir',
        ),
        migrations.RemoveField(
            model_name='env',
            name='git_repo_update',
        ),
        migrations.RemoveField(
            model_name='env',
            name='middleware_dir',
        ),
        migrations.RemoveField(
            model_name='env',
            name='patch',
        ),
        migrations.RemoveField(
            model_name='env',
            name='repo_dir',
        ),
        migrations.RemoveField(
            model_name='env',
            name='repo_dir_update',
        ),
        migrations.RemoveField(
            model_name='env',
            name='version',
        ),
        migrations.AlterField(
            model_name='env',
            name='api_port',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='env',
            name='app_dir',
            field=models.CharField(default='way_box_app_v2', max_length=200),
        ),
    ]
