# Generated by Django 2.0.8 on 2018-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0036_auto_20181109_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='branche',
            field=models.CharField(default='master', max_length=200),
        ),
    ]
