# Generated by Django 2.0.8 on 2018-11-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0038_auto_20181109_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='portal_url',
            field=models.CharField(default='portal.way-connect.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='env',
            name='root_dir',
            field=models.CharField(default='/home/bouraoui', max_length=200),
        ),
    ]
