# Generated by Django 2.0.8 on 2018-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0039_auto_20181109_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='hash_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
