# Generated by Django 2.0.8 on 2018-11-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0040_env_hash_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='env',
            old_name='branche',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='env',
            old_name='hash_code',
            new_name='commit_hash',
        ),
    ]
