# Generated by Django 2.1.3 on 2018-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_config', '0041_auto_20181109_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env',
            name='ftp_host',
        ),
        migrations.RemoveField(
            model_name='env',
            name='ftp_password',
        ),
        migrations.RemoveField(
            model_name='env',
            name='ftp_user',
        ),
        migrations.AddField(
            model_name='env',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
