# Generated by Django 2.2.dev20180916104534 on 2018-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dhcpcd', models.CharField(default='', max_length=200)),
                ('dnsmasq', models.CharField(default='', max_length=200)),
                ('hostapd', models.CharField(default='', max_length=200)),
                ('nodogsplash', models.CharField(default='', max_length=200)),
                ('internet_connection', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
