# Generated by Django 2.2.dev20180916104534 on 2018-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemStatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='dhcpcd_message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='dnsmasq_message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='hostapd_message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='internet_connection_message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='nodogsplash_message',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='dhcpcd',
            field=models.BooleanField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='dnsmasq',
            field=models.BooleanField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='hostapd',
            field=models.BooleanField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='internet_connection',
            field=models.BooleanField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='nodogsplash',
            field=models.BooleanField(default='', max_length=200),
        ),
    ]
