# Generated by Django 2.2.dev20180916104534 on 2018-11-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemStatus', '0002_auto_20181106_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='dhcpcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='hostapd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='internet_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='nodogsplash',
            field=models.BooleanField(default=False),
        ),
    ]
