# Generated by Django 2.2.dev20180916104534 on 2018-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemStatus', '0003_auto_20181106_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='dhcpcd_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='dnsmasq',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='dnsmasq_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='hostapd_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='internet_connection_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='nodogsplash_message',
            field=models.TextField(default=''),
        ),
    ]
