# Generated by Django 2.2.dev20180916104534 on 2018-11-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemStatus', '0004_auto_20181106_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='connected_clients',
            field=models.IntegerField(default=0),
        ),
    ]
