# Generated by Django 2.2.dev20180916104534 on 2018-10-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20181012_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='aflinks',
            name='type',
            field=models.CharField(choices=[('AF_LINK', 'AF_LINK'), ('AF_INET', 'AF_INET'), ('AF_INET6', 'AF_INET6')], default='', max_length=200),
        ),
    ]
